=== MIKE_SHORT_PRESENTION ===
Mike is fan of sports.
-> END

// AFFINITY VARS //
VAR V_AFFINITY_MIKE_MIKE = 100
VAR V_AFFINITY_MIKE_RACHELLE = 100
VAR V_AFFINITY_MIKE_STEVE = 100
VAR V_AFFINITY_MIKE_VANESSA = 100
VAR V_AFFINITY_MIKE_YOU = 100
// STATS VARS //
VAR V_STAT_FORCE_MIKE = 100
VAR V_STAT_SMART_MIKE = 100
VAR V_STAT_SPEED_MIKE = 100