=== RACHELLE_SHORT_PRESENTION ===
Rachelle is fan of sports.
-> END

// AFFINITY VARS //
VAR V_AFFINITY_RACHELLE_MIKE = 100
VAR V_AFFINITY_RACHELLE_RACHELLE = 100
VAR V_AFFINITY_RACHELLE_STEVE = 100
VAR V_AFFINITY_RACHELLE_VANESSA = 100
VAR V_AFFINITY_RACHELLE_YOU = 100
// STATS VARS //
VAR V_STAT_FORCE_RACHELLE = 100
VAR V_STAT_SMART_RACHELLE = 100
VAR V_STAT_SPEED_RACHELLE = 100