=== STEVE_SHORT_PRESENTION ===
Mike is fan of sports.
-> END

// AFFINITY VARS //
VAR V_AFFINITY_STEVE_MIKE = 100
VAR V_AFFINITY_STEVE_RACHELLE = 100
VAR V_AFFINITY_STEVE_STEVE = 100
VAR V_AFFINITY_STEVE_VANESSA = 100
VAR V_AFFINITY_STEVE_YOU = 100
// STATS VARS //
VAR V_STAT_FORCE_STEVE = 100
VAR V_STAT_SMART_STEVE = 100
VAR V_STAT_SPEED_STEVE = 100