=== VANESSA_SHORT_PRESENTION ===
Mike is fan of sports.
-> END

// AFFINITY VARS //
VAR V_AFFINITY_VANESSA_MIKE = 100
VAR V_AFFINITY_VANESSA_RACHELLE = 100
VAR V_AFFINITY_VANESSA_STEVE = 100
VAR V_AFFINITY_VANESSA_VANESSA = 100
VAR V_AFFINITY_VANESSA_YOU = 100
// STATS VARS //
VAR V_STAT_FORCE_VANESSA = 100
VAR V_STAT_SMART_VANESSA = 100
VAR V_STAT_SPEED_VANESSA = 100