//
// NAME : DAVID
//
// AFFINITY VARS //
VAR V_AFFINITY_YOU_MIKE = 100
VAR V_AFFINITY_YOU_RACHELLE = 100
VAR V_AFFINITY_YOU_STEVE = 100
VAR V_AFFINITY_YOU_VANESSA = 100
VAR V_AFFINITY_YOU_YOU = 100
// STATS VARS //
VAR V_STAT_FORCE_YOU = 100
VAR V_STAT_SMART_YOU = 100
VAR V_STAT_SPEED_YOU = 100