// CONST //
CONST C_GAME_VERSION = "0.0.1"
CONST C_ZERO = 0
CONST C_STAT_LIL_UP = 5
CONST C_STAT_MEDIUM_UP = 10
CONST C_STAT_HUGE_UP = 15
CONST C_STAT_LIL_DOWN = -10
CONST C_STAT_MEDIUM_DOWN = -15
CONST C_STAT_HUGE_DOWN = -20
// LIST //
LIST L_DAYS = Monday ,Tuesday ,Wednesday ,Thursday ,Friday , Saturday, Sunday
LIST L_AFFINITY_CLASS = LOVE, LIKE, NEUTRAL, DISLIKE, HATE
LIST L_ACTORS = MIKE, RACHELLE, STEVE, VANESSA, YOU, FACELESS